#!/bin/bash

. cmd/config

error_message(){
    echo "move { own | abs | rel }  [<lat or x> <lon or y>]"
    exit 1
}

if [ $# != 1 ] && [ $# != 3 ]; then
    error_message 
fi

if [ $1 = "own" ]; then
    cmd_i setmapcenter 0
else
    if [ $# != 3 ]; then
	error_message
    fi
    case $1 in
	"abs") cmd_iiff setmapcenter 1 0 $2 $3;;
	"rel") cmd_iiff setmapcenter 2 0 $2 $3;;
	*) error_message;;
    esac
fi

