#!/bin/bash

RUN="caws run "
LS="ls -lag "
FILTER_IN="caws setfltrinchs "
FILTER_OUT="caws setfltroutchs "
FILTER="caws genfltr "
CHANNEL="caws gench "
FSET="caws setfltrpar "

env=`uname`
cpu=`uname -p`

if [ $cpu = "x86_64" ]; then
    export path_aws=/mnt/c/cygwin64/home/yhmtmt/tools/awsv1
    export path_data=/mnt/d/aws
else
    export path_aws=/mnt/aws
    export path_data=/mnt/aws
fi
