#!/bin/sh

ch_state=state
ch_state_sim=state_sim
ch_env=env
ch_ais_obj=ais_obj

ch_engstate=engstate
ch_engstate_sim=engstate_sim
ch_wp=wp
ch_ap_inst=ap_inst
ch_img=img
ch_map=map

ch_nmea_data_all=nmea_data_all
ch_nmea_data_ais=nmea_data_ais

ch_n2k_data=n2k_data

ch_ctrl_ui_to_ap=ch_ctrl_ui_to_ap
ch_ctrl_ap_to_ui=ch_ctrl_ap_to_ui
ch_ctrl_ap_to_ctrl=ch_ctrl_ap_to_ctrl
ch_ctrl_ctrl_to_ap=ch_ctrl_ctrl_to_ap

radar_image=radar_image
radar_state=radar_state
radar_ctrl=radar_ctrl

ch_time_sync=time_sync

#channel sharing

schh2l="$ch_ctrl_ap_to_ctrl"
schl2h="$ch_nmea_data $ch_ctrl_ctrl_to_ap"
