#!/bin/sh

. ../config

if [ $env = "Linux" ]; then
    width=960
    height=540
else
    width=1920
    height=1080
fi

joystick=0

path_fshader=$path_aws/lib/ui_manager.fs
path_vshader=$path_aws/lib/ui_manager.vs
path_fnttex=$path_aws/lib/gothic40.png
path_fnttexinf=$path_aws/lib/gothic40.fontsettings

nf=223
flah=218
hfah=208
slah=198
dsah=152
stp=127
dsas=100
slas=55
hfas=45
flas=35

has=255
s20=213
s10=173
mds=133
p10=89
p20=45
hap=0
