#!/bin/sh

. ../config

if [ $env = "Linux" ]; then
    width=960
    height=540
else
    width=1920
    height=1080
fi

joystick=0

path_fshader=$path_aws/lib/ui_manager.fs
path_vshader=$path_aws/lib/ui_manager.vs
path_fnttex=$path_aws/lib/gothic40.png
path_fnttexinf=$path_aws/lib/gothic40.fontsettings
quit_script="stop"
path_quit_script=`pwd`
