#!/bin/sh

. ../config

eng_max=220
eng_min=80
rev_max=5500
rev_min=700
pc=1.0
ic=0.01
dc=0.0
ps=0.1
is=0.01
ds=0.0
prev=0.1
irev=0.01
drev=0.0

smax=15
smin=10

alpha_tbl_stable_rpm=0.05
alpha_rud_mid=0.01
alpha_yaw_bias=0.01
alpha_flw=0.1
twindow_stability_check=3
devyaw=3.0
devcog=3.0
devsog=1.0
devrev=500
fctrl_state=$path_aws/ctrl_state.json

