#!/bin/sh

. ../config

eng_max=240
eng_min=60
rev_max=5500
rev_min=700
pc=1.0
ic=0.001
dc=0.1
ps=0.1
is=0.001
ds=0.1
prev=0.1
irev=0.001
drev=0.1

smax=20
smin=2

alpha_tbl_stable_rpm=0.005
alpha_rud_mid=0.001
alpha_yaw_bias=0.001
alpha_flw=0.001
twindow_stability_check=3
devyaw=0.052
devcog=0.052
devsog=1.0
devrev=500
fctrl_state=ctrl_state.json

