#!/bin/bash

verb=n
go=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "map_manager") map_manager=${param[1]};;      # name of map filter
	    "ch_map") ch_map=${param[1]};; # map channel
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi    
done

. ../config
. ./config_map

if [ -z "$ch_map" ]; then
   ch_map=map
   $CHANNEL map $ch_map
fi

if [ -z "$map" ]; then
    map=map
fi

$FILTER map_manager $map_manager
$FSET $map_manager ch_map $ch_map
$FSET $map_manager path $path_map

$RUN $map_manager
