#!/bin/bash

verb=n
go=n
radar_gxhd="radar_gxhd"
state=
radar_state=
radar_image=
radar_ctrl=

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
        param=(${arg//=/ })
        case ${param[0]} in
	    "radar_gxhd")radar_gxhd=${param[1]};;
            "state")state=${param[1]};;
            "radar_state")radar_state=${param[1]};;
            "radar_image")radar_image=${param[1]};;
	    "radar_ctrl")radar_ctrl=${param[1]};;
            "verb") verb=${param[1]};;
            "go") go=${param[1]};;
        esac
    fi        
done

. ./config_radar

if [ -z "$state" ]; then
   state="state"
   `$CHANNEL state $state`
fi

if [ -z "$radar_state" ]; then
   radar_state="radar_state"
   `$CHANNEL radar_state $radar_state`
fi

if [ -z "$radar_image" ]; then
   radar_image="radar_image"
   `$CHANNEL radar_image $radar_image`
fi

if [ -z "$radar_ctrl" ]; then
   radar_ctrl="radar_ctrl"
   `$CHANNEL radar_ctrl $radar_ctrl`
fi

$FILTER radar_gxhd $radar_gxhd
$FSET $radar_gxhd state $state
$FSET $radar_gxhd radar_state $radar_state
$FSET $radar_gxhd radar_image $radar_image
$FSET $radar_gxhd radar_ctrl $radar_ctrl

$RUN $radar_gxhd

