#!/bin/bash

verb=n
go=n
svr=n
data_sharing_manager=data_sharing_manager

mode=normal

for arg in $*
do

    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "data_sharing_manager")data_sharing_manager=${param[1]};;
	    "svr")svr=${param[1]};;
	    "in")in=${param[1]};;
	    "out")out=${param[2]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
	mode=normal
    else
	case $arg in
	    "-i")mode=in
		 continue;;
	    "-o")mode=out
		 continue;;
	esac

	case $mode in
	    "in") ich+="$arg ";;
	    "out") och+="$arg ";;
	esac
    fi        
done

. ../config
. ../config_share

$FILTER data_sharing_manager $data_sharing_manager
echo $ich
$FILTER_IN $data_sharing_manager $ich
echo $och
$FILTER_OUT $data_sharing_manager $och
if [ $svr = "y" ]; then
    $FSET $data_sharing_manager port $port_svr
else
    echo "Data sharing manager $ip_svr $port_svr"
    $FSET $data_sharing_manager host_dst $ip_svr port_dst $port_svr
fi

#$FSET $data_sharing_manager verb $verb 

$RUN $data_sharing_manager
