#!/bin/bash

dbg_ui=n
dbg_ap=n
dbg_n2k=n
dbg_obj=n
dbg_sync=n
dbg_share=y
dbg_wp=n
dbg_sim=n

sim=n
replay=n

. ../config
. ../config_channel

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "sim") sim=${param[1]};;
	    "dbg_n2k") dbg_n2k=${param[1]};;
	    "replay") replay=${param[1]};;
	    "tstart") tstart=${param[1]};;
	esac
    fi    
done


$CHANNEL nmea_data $ch_nmea_data_all
$CHANNEL nmea_data $ch_nmea_data_ais
$CHANNEL n2k_data $ch_n2k_data    
$CHANNEL time_sync $ch_time_sync

$CHANNEL state $ch_state
$CHANNEL engstate $ch_engstate
$CHANNEL wp $ch_wp
$CHANNEL ais_obj $ch_ais_obj
$CHANNEL map $ch_map

$CHANNEL ctrl_data $ch_ctrl_ui_to_ap
$CHANNEL ctrl_data $ch_ctrl_ap_to_ui
$CHANNEL ctrl_data $ch_ctrl_ap_to_ctrl
$CHANNEL ctrl_data $ch_ctrl_ctrl_to_ap

if [ $replay = "n" ]; then    
    caws clock run
else
    echo "Replay mode start from $tstart"
    caws clock run -s $tstart -o n
fi


replay_sync=n
replay_nmea=n
log_nmea=y
log_ctrl=y
if [ $replay = "nmea" ]; then
    echo "Replay NMEA data at state filter."
    replay_nmea=y
    replay_sync=y
    log_nmea=n
    log_ctrl=n
fi

replay_ui=n
if [ $replay = "ui" ]; then
    echo "Replay Control data at ui filter."
    replay_ui=y
    log_nmea=n
    log_ctrl=n
fi

if [ $sim = "y" ] || [ $replay = "ui" ]; then
    ch_nmea_state_to_dev=nmea_state_to_dev
    ch_nmea_state_from_dev=nmea_state_from_dev
    $CHANNEL nmea $ch_nmea_state_to_dev
    $CHANNEL nmea $ch_nmea_state_from_dev    
    $CHANNEL state $ch_state_sim
    $CHANNEL engstate $ch_engstate_sim
    
    echo "Setting up SIM"    
    ./sim ch_state=$ch_state_sim ch_engstate=$ch_engstate_sim ch_ctrl_in=$ch_ctrl_ap_to_ctrl ch_ctrl_out=$ch_ctrl_ctrl_to_ap ch_state_sim=$ch_state_sim ch_engstate_sim=$ch_engstate_sim stime=$stime ch_gps_nmea=$ch_nmea_state_from_dev ch_eng_n2k_data=$ch_n2k_data

    echo "Setting up virtual V104"
    ../lsys/nmea nmea=v104 ch_nmea_to_dev=$ch_nmea_state_to_dev ch_nmea_from_dev=$ch_nmea_state_from_dev ch_nmea_data=$ch_nmea_data_all
    
else
    $CHANNEL radar_state $radar_state
    $CHANNEL radar_image $radar_image
    $CHANNEL radar_ctrl $radar_ctrl
    
    echo "Setting up SYNC"
    ./sync ch_time_sync=$ch_time_sync replay=$replay_sync
    
    # n2k interface
    echo "Setting up N2K"
    ./n2k ch_n2k_data=$ch_n2k_data verb=$dbg_n2k

    # radar
    echo "Setting up Radar"
    ./radar radar="radar" state=$ch_state radar_state=$radar_state radar_image=$radar_image radar_ctrl=$radar_ctrl

    # channel sharing
    echo "Settng up CHS"
    ./share data_sharing_manager=share -i $schh2l -o $schl2h verb=$dbg_share svr=n   
fi

echo "Setting up STATE"
./state ch_state=$ch_state ch_engstate=$ch_engstate ch_nmea_data_in=$ch_nmea_data_all ch_nmea_data_out=$ch_nmea_data_ais ch_n2k_data_in=$ch_n2k_data ch_time_sync=$ch_time_sync log_nmea=$log_nmea replay=$replay_nmea

# object manager
echo "Setting up OBJM"
./obj ch_state=$ch_state ch_nmea_data=$ch_nmea_data_ais ch_ais_obj=$ch_ais_obj verb=$dbg_obj

# autopilot
echo "Setting up AP"

./ap ch_state=$ch_state ch_engstate=$ch_engstate ch_wp=$ch_wp ch_ctrl_stat=$ch_ctrl_stat ch_ctrl_inst=$ch_ctrl_ap ch_ap_inst=$ch_ap_inst ch_ctrl_from_ui=$ch_ctrl_ui_to_ap ch_ctrl_from_ctrl=$ch_ctrl_ctrl_to_ap ch_ctrl_to_ui=$ch_ctrl_ap_to_ui ch_ctrl_to_ctrl=$ch_ctrl_ap_to_ctrl ch_ctrl_verb=$dbg_ap

# waypoint manager
echo "Setting up WPM"
./wp ch_state=$ch_state ch_wp=$ch_wp verb=$dbg_wp

# Map manager
echo "Setting up MAP"
./map map_manager=map ch_map=$ch_map

# user interface
echo "Setting up UI"
./ui ch_state=$ch_state ch_engstate=$ch_engstate ch_wp=$ch_wp ch_ctrl_in=$ch_ctrl_ap_to_ui ch_ctrl_out=$ch_ctrl_ui_to_ap ch_ais_obj=$ch_ais_obj ch_map=$ch_map verb=$dbg_ui ch_radar_state=$radar_state ch_radar_image=$radar_image ch_radar_ctrl=$radar_ctrl log_ctrl=$log_ctrl replay=$replay_ui

