#!/bin/bash


verb=n
go=n
waypoint_manager=wpm

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "waypoint_manager") waypoint_manager=${param[1]};;
	    "ch_state") ch_state=${param[1]};;
	    "ch_wp") ch_wp=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi
done

. ../config

$FILTER waypoint_manager $waypoint_manager
$FSET $waypoint_manager ch_state $ch_state
$FSET $waypoint_manager ch_wp $ch_wp
$FSET $waypoint_manager path $path_data
#$FSET $waypoint_manager verb $verb

$RUN $waypoint_manager
