#!/bin/sh
. ../config

dev=/dev/zgpio0

meng_max_rmc=21
meng_nuf_rmc=91
meng_nut_rmc=107
meng_nub_rmc=124
meng_min_rmc=151

seng_max_rmc=24
seng_nuf_rmc=91
seng_nut_rmc=107
seng_nub_rmc=124
seng_min_rmc=151

rud_max_rmc=220
rud_nut_rmc=111
rud_min_rmc=0

rud_sta_max=15
rud_sta_nut=90
rud_sta_min=172

meng_max=228
meng_nuf=151
meng_nut=129
meng_nub=104
meng_min=78

seng_max=226
seng_nuf=153
seng_nut=130
seng_nub=103
seng_min=78

rud_max=5
rud_nut=127
rud_min=250

rud_sta_out_max=243
rud_sta_out_nut=143
rud_sta_out_min=39

awsrud=127
awsmeng=127
awsseng=127

