#!/bin/bash


verb=n
go=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "ctrl") ctrl=${param[1]};;      # name of ctrl $FILTER
	    "ch_ctrl_ui") ch_ctrl_ui=${param[1]};;  # state of my own ship
	    "ch_ctrl_ap") ch_ctrl_ap=${param[1]};; # state of controler
	    "ch_ctrl_stat") ch_ctrl_stat=${param[1]};;# instruction to autopilot
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi    
done

if [ -z "$ctrl" ]; then
    echo "ctrl ctrl=<name> ch_ctrl_ui=<control from ui> ch_ctrl_ap=<control from ap> ch_ctrl_stat=<control status> verb=<y or n> go=<y or n>"
fi

. ../config
. ./config_ctrl

$FILTER control_aws1 $ctrl
if [ -n "$ch_ctrl_ui" ]; then
    $FSET $ctrl ch_ctrl_ui $ch_ctrl_ui
fi

if [ -n "$ch_ctrl_ap" ]; then
    $FSET $ctrl ch_ctrl_ap $ch_ctrl_ap
fi

$FSET $ctrl ch_ctrl_stat $ch_ctrl_stat
$FSET $ctrl device $dev
$FSET $ctrl verb $verb
$FSET $ctrl sim no

$FSET $ctrl rud_sta_max $rud_sta_max rud_sta_nut $rud_sta_nut rud_sta_min $rud_sta_min
$FSET $ctrl eng_max $eng_max eng_nuf $eng_nuf eng_nut $eng_nut eng_nub $eng_nub eng_min $eng_min
$FSET $ctrl rud_max $rud_max rud_nut $rud_nut rud_min $rud_min
$FSET $ctrl awsrud $awsrud awseng $awseng

$RUN $ctrl

