#!/bin/bash


verb=n
go=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "ctrl") ctrl=${param[1]};;      # name of ctrl $FILTER
	    "ch_ctrl_ui") ch_ctrl_ui=${param[1]};;    # state of my own ship
	    "ch_ctrl_ap1") ch_ctrl_ap1=${param[1]};; # state of controler
	    "ch_ctrl_ap2") ch_ctrl_ap2=${param[1]};; # instruction to controler
	    "ch_ctrl_stat") ch_ctrl_stat=${param[1]};;# instruction to autopilot
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi    
done

if [ -z "$ctrl" ]; then
    echo "ctrl ctrl=<name> ch_ctrl_ui=<control from ui> ch_ctrl_ap1=<control from ap1> ch_ctrl_ap2=<control from ap2> ch_ctrl_stat=<control status> verb=<y or n> go=<y or n>"
fi

. ../config
. ./config_ctrl

$FILTER control_aws1 $ctrl
if [ -n "$ch_ctrl_ui" ]; then
    $FSET $ctrl ch_ctrl_ui $ch_ctrl_ui
fi

if [ -n "$ch_ctrl_ap1" ]; then
    $FSET $ctrl ch_ctrl_ap1 $ch_ctrl_ap1
fi

if [ -n "$ch_ctrl_ap2" ]; then
    $FSET $ctrl ch_ctrl_ap2 $ch_ctrl_ap2
fi

$FSET $ctrl ch_ctrl_stat $ch_ctrl_stat
$FSET $ctrl device $dev
$FSET $ctrl verb $verb
$FSET $ctrl sim no

$FSET $ctrl eng_max_rmc $eng_max_rmc eng_nuf_rmc $eng_nuf_rmc eng_nut_rmc $eng_nut_rmc eng_nub_rmc $eng_nub_rmc eng_min_rmc $eng_min_rmc
$FSET $ctrl rud_max_rmc $rud_max_rmc rud_nut_rmc $rud_nut_rmc rud_min_rmc $rud_min_rmc
$FSET $ctrl rud_sta_max $rud_sta_max rud_sta_nut $rud_sta_nut rud_sta_min $rud_sta_min
$FSET $ctrl eng_max $eng_max eng_nuf $eng_nuf eng_nut $eng_nut eng_nub $eng_nub eng_min $eng_min
$FSET $ctrl rud_max $rud_max rud_nut $rud_nut rud_min $rud_min
$FSET $ctrl rud_sta_out_max $rud_sta_out_max rud_sta_out_nut $rud_sta_out_nut rud_sta_out_min $rud_sta_out_min
$FSET $ctrl awsrud $awsrud awseng $awseng

$RUN $ctrl

