#!/bin/bash

verb=n
go=n
nmea=

ch_nmea_in=
ch_nmea_out=
ch_nmea_to_dev=
ch_nmea_from_dev=

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "nmea")nmea=${param[1]};;
	    "ch_nmea_in")ch_nmea_in=${param[1]};;
	    "ch_nmea_out")ch_nmea_out=${param[1]};;
	    "ch_nmea_data")ch_nmea_data=${param[1]};;
	    "ch_nmea_to_dev")ch_nmea_to_dev=${param[1]};;
	    "ch_nmea_from_dev")ch_nmea_from_dev=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi        
done


if [ -z "$nmea" ]; then
    echo "nmea nmea=<device> [ch_nmea_in=<input channel> ch_nmea_out<output channel> verb=<y or n> go=<y or n>]"
    exit
fi

. ../config
. ./config_$nmea

echo "Setting up ${nmea}'s nmea filter on $dev $br"

if [ -z "$ch_nmea_in" ]; then
    ch_nmea_in=${nmea}_in
    echo "$CHANNEL $ch_nmea_in is instantiated."
    $CHANNEL nmea $ch_nmea_in
fi

if [ -z "$ch_nmea_out" ]; then
    ch_nmea_out=${nmea}_out
    echo "$CHANNEL $ch_nmea_out is instantiated."    
    $CHANNEL nmea $ch_nmea_out
fi


if [ -z "$ch_nmea_data" ]; then
    ch_nmea_data=${nmea}_data_out
    echo "$CHANNEL nmea_data $ch_nmea_data is instantiated."
    $CHANNEL nmea_data $ch_nmea_data
fi

$FILTER nmea0183_device $nmea
$FSET $nmea bps $br
$FSET $nmea verb $verb
$FSET $nmea data_out $ch_nmea_data
# only used in simulation mode (nmea sentences are from other filters emulating devices)
if [ -n "$ch_nmea_to_dev" ] && [ -n "$ch_nmea_from_dev" ]; then
    $FSET $nmea src CHAN
    $FSET $nmea fnmea $dev
    $FSET $nmea to_dev $ch_nmea_to_dev from_dev $ch_nmea_from_dev
else
    $FSET $nmea src COM
    $FSET $nmea fnmea $dev
    $FSET $nmea nmea_in $ch_nmea_in nmea_out $ch_nmea_out
fi
$RUN $nmea

if [ $go = "y" ]; then
    caws clock run
fi
