#!/bin/bash

verb=n
go=n
nmea=

ch_nmea_in=
ch_nmea_out=

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "nmea")nmea=${param[1]};;
	    "ch_nmea_in")ch_nmea_in=${param[1]};;
	    "ch_nmea_out")ch_nmea_out=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi        
done


if [ -z "$nmea" ]; then
    echo "nmea nmea=<device> [ch_nmea_in=<input channel> ch_nmea_out<output channel> verb=<y or n> go=<y or n>]"
    exit
fi

. ../config
. ./config_$nmea

echo "Setting up ${nmea}'s nmea filter on $dev $br"

if [ -z "$ch_nmea_in" ]; then
    ch_nmea_in=${nmea}_in
    echo "$CHANNEL $ch_nmea_in is instantiated."
    $CHANNEL nmea $ch_nmea_in
fi

if [ -z "$ch_nmea_out" ]; then
    ch_nmae_out=${nmea}_out
    echo "$CHANNEL $ch_nmea_out is instantiated."    
    $CHANNEL nmea $ch_nmea_out
fi

$FILTER nmea0183_device $nmea
$FILTER_IN $nmea $ch_nmea_in
$FILTER_OUT $nmea $ch_nmea_out
$FSET $nmea src COM
$FSET $nmea fnmea $dev
$FSET $nmea bps $br
$FSET $nmea verb $verb

$RUN $nmea
