#!/bin/bash

verb=n
go=n
nmea=

ch_nmea_in=
ch_nmea_out=

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "nmea")nmea=${param[1]};;
	    "ch_nmea_in")ch_nmea_in=${param[1]};;
	    "ch_nmea_out")ch_nmea_out=${param[1]};;
	    "ch_data_out")ch_data_out=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi        
done


if [ -z "$nmea" ]; then
    echo "nmea nmea=<device> [ch_nmea_in=<input channel> ch_nmea_out<output channel> verb=<y or n> go=<y or n>]"
    exit
fi

. ../config
. ./config_$nmea

echo "Setting up ${nmea}'s nmea filter on $dev $br"

if [ -z "$ch_nmea_in" ]; then
    ch_nmea_in=${nmea}_in
    echo "$CHANNEL $ch_nmea_in is instantiated."
    $CHANNEL nmea $ch_nmea_in
fi

if [ -z "$ch_nmea_out" ]; then
    ch_nmea_out=${nmea}_out
    echo "$CHANNEL $ch_nmea_out is instantiated."    
    $CHANNEL nmea $ch_nmea_out
fi


if [ -z "$ch_data_out" ]; then
    ch_data_out=${nmea}_data_out
    echo "$CHANNEL nmea_data $ch_data_out is instantiated."
    $CHANNEL nmea_data $ch_data_out
fi

$FILTER nmea0183_device $nmea
$FSET $nmea src COM
$FSET $nmea fnmea $dev
$FSET $nmea bps $br
$FSET $nmea verb $verb
$FSET $nmea nmea_in $ch_nmea_in nmea_out $ch_nmea_out data_out $ch_data_out
$RUN $nmea
