#!/bin/bash
. ../config
verb=n
go=n

gff=n
ais=n
v104=n
wx220=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "sw")sw=${param[1]};;
	    "ch_nmea_in")ch_nmea_in=${param[1]};;
	    "ch_nmea_out")ch_nmea_out=${param[1]};;
	    "ch_state")ch_state=${param[1]};;
	    "ch_ais_obj")ch_ais_obj=${param[1]};;
	    "ch_nmea_data")ch_nmea_data=${param[1]};;
	    "gff") gff=${param[1]};;
	    "ais") ais=${param[1]};;
	    "v104") v104=${param[1]};;
	    "wx220") wx220=${param[1]};;  
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi        
done

if [ -z $sw ]; then
    echo "nmea_manager sw=<name> ch_nmea_in=<nmea input> ch_nmea_out=<nmea output> gff=<y or n> ais=<y or n> ap=<y or n> gps=<y or n> go=<y or n> verb=<y or n>"
    exit
fi

if [ -z $ch_nmea_in ]; then
    ch_nmea_in=${sw}_nmea_in
    $CHANNEL nmea $ch_nmea_in
fi


if [ -z $ch_nmea_out ]; then
    ch_nmea_out=${sw}_nmea_out
    $CHANNEL nmea $ch_nmea_out
fi

$FILTER nmea0183_manager $sw
$FSET $sw aws_nmea_i ${sw}_nmea_out
$FSET $sw aws_nmea_o ${sw}_nmea_in
$FSET $sw aws_ctrl no
$FSET $sw awsint 1
$FSET $sw verb $verb

if [ -n "$ch_state" ]; then
    $FSET $sw state $ch_state
fi

if [ $gff = y ]; then
    $CHANNEL nmea gff_nmea_in
    $CHANNEL nmea gff_nmea_out
    $FSET $sw gff_nmea_i gff_nmea_in
    $FSET $sw gff_nmea_o gff_nmea_out
    $FSET $sw gffint 1

    ./nmea nmea=gff ch_nmea_in=gff_nmea_out ch_nmea_out=gff_nmea_in ch_nmea_data=$ch_nmea_data verb=$verb
fi

if [ $ais = y ]; then
    $CHANNEL nmea ais_nmea_in
    $CHANNEL nmea ais_nmea_out
    $FSET $sw ais_obj $ch_ais_obj
    $FSET $sw ais_nmea_i ais_nmea_in
    $FSET $sw ais_nmea_o ais_nmea_out
    $FSET $sw aisint 1

    ./nmea nmea=ais ch_nmea_in=ais_nmea_out ch_nmea_out=ais_nmea_in  ch_nmea_data=$ch_nmea_data verb=$verb
fi

if [ $wx220 = y ]; then
    $CHANNEL nmea wx220_nmea_in
    $CHANNEL nmea wx220_nmea_out
    $FSET $sw wx220_nmea_i wx220_nmea_in
    $FSET $sw wx220_nmea_o wx220_nmea_out
    $FSET $sw wx220int 1

    ./nmea nmea=wx220 ch_nmea_in=wx220_nmea_out ch_nmea_out=wx220_nmea_in ch_nmea_data=$ch_nmea_data verb=$verb
fi

if [ $v104 = y ]; then
    $CHANNEL nmea v104_nmea_in
    $CHANNEL nmea v104_nmea_out
    $FSET $sw v104_nmea_i v104_nmea_in
    $FSET $sw v104_nmea_o v104_nmea_out
    $FSET $sw v104int 1

    ./nmea nmea=v104 ch_nmea_in=v104_nmea_out ch_nmea_out=v104_nmea_in ch_nmea_data=$ch_nmea_data verb=$verb
fi

$RUN $sw
