#!/bin/bash
verb=n
go=n

gff=y
ais=y
gps=n
v104=y
wx220=y

dbg_ctrl=n
dbg_sw=n
dbg_sync=n
dbg_share=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "ctrl") ctrl=${param[1]};;      # name of ctrl filter
	    "ch_ctrl_ui") ch_ctrl_ui=${param[1]};;    # state of my own ship
	    "ch_ctrl_ap") ch_ctrl_ap=${param[1]};; # state of controler
	    "ch_ctrl_stat") ch_ctrl_stat=${param[1]};;# instruction to autopilot
	    "gff") gff=${param[1]};;
	    "ais") ais=${param[1]};;
	    "gps") gps=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi    
done

. ../config
. ../config_channel

caws clock run

$CHANNEL state $ch_state
$CHANNEL ctrl_data $ch_ctrl_ctrl_to_ap
$CHANNEL ctrl_data $ch_ctrl_ap_to_ctrl
$CHANNEL nmea_data $ch_nmea_data
$CHANNEL time_sync $ch_time_sync

./ctrl ctrl=ctrl ch_ctrl_in=$ch_ctrl_ap_to_ctrl ch_ctrl_out=$ch_ctrl_ctrl_to_ap verb=$dbg_ctrl

./nmea_devices gff=$gff ais=$ais v104=$v104 wx220=$wx220 ch_nmea_data=$ch_nmea_data verb=$dbg_sw #future version

./share share=share -i $schl2h -o $schh2l verb=$dbg_share svr=y

./sync ch_time_sync=$ch_time_sync

