#!/bin/bash
verb=n
go=n

gff=y
ais=y
gps=n
v104=y
wx220=y

dbg_ctrl=n
dbg_sw=n
dbg_sync=n
dbg_share=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "gff") gff=${param[1]};;
	    "ais") ais=${param[1]};;
	    "gps") gps=${param[1]};;
	    "verb") verb=${param[1]};;
	    "go") go=${param[1]};;
	esac
    fi    
done

. ../config
. ../config_channel

caws clock run

$CHANNEL state $ch_state
$CHANNEL ctrl_data $ch_ctrl_ctrl_to_ap
$CHANNEL ctrl_data $ch_ctrl_ap_to_ctrl
$CHANNEL nmea_data $ch_nmea_data_all

echo "Setting up controller"
./ctrl ctrl=ctrl ch_ctrl_in=$ch_ctrl_ap_to_ctrl ch_ctrl_out=$ch_ctrl_ctrl_to_ap verb=$dbg_ctrl

echo "Setting up NMEA devices"
./nmea_devices gff=$gff ais=$ais v104=$v104 wx220=$wx220 ch_nmea_data=$ch_nmea_data_all verb=$dbg_sw #future version

echo "Setting up data sharing manager"
./share share=share -i $schl2h -o $schh2l verb=$dbg_share svr=y

echo "Setting up time synchronizer"
./sync

