#!/bin/bash

verb=n
go=n
svr=n
tsync=time_sync

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "tsync")tsync=${param[1]};;
	    "ch_time_sync")ch_time_sync=${param[1]};;	    
	    "verb") verb=${param[1]};;
	esac
    fi    
done

. ./config_sync

$FILTER time_sync $tsync
$FSET $tsync ch_time_sync $ch_time_sync
$FSET $tsync port $port_svr
$FSET $tsync verb $verb

$RUN $tsync
