#!/bin/bash

. cmd/config

error_message(){
    echo "gain {auto | <gain>}"
    exit 1
}

if [ $# != 1 ]; then
    error_message
fi

case $1 in
    "auto") cmd_i setrdgain 1 ;;
    * ) cmd_ii setrdgain 0 $1 ;;
esac

