#!/bin/bash

. cmd/config

error_message(){
	echo "rain { off | <value>}"
	exit 1
}

if [ $# != 1 ]; then
   error_message()
fi

case $1 in
"off") cmd_i setrdrain -1 ;;
* ) cmd_ii setrdrain 0 $1 ;;
esac
